name: Lemming

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  lemming:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - name: Set up Python 3.11
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4.6.0
        with:
          python-version: "3.11"
      - name: Install Lemming
        # ! Hey! If you're copy-pasting this file, then choose the the commented out command
        run: |
          python -m pip install "git+https://github.com/koviubi56/lemming.git"
        # python -m pip install -U python-lemming
      - name: Run lemming
        run: |
          python -m lemming check . -v
